### ISSUE TITLE
Incorrect Rotation for Principal Axes of Inertia

### ISSUE THREAD

**Issue by tolomeis** [isaac-sim/urdf-importer-extension#2]
I noticed that principal axes of inertia are not correctly computed. I think this should be fixed or mentioned in the known issues as it may lead to completely wrong behaviours.

**Description:**
The URDF importer fails to correctly diagonalize the inertia matrix and compute the associated rotation when converting from URDF to USD format. This leads to incorrect results when the inertia matrix in the URDF contains off-diagonal elements.

**Steps to Reproduce:**

1. Use the provided URDF snippet containing a link with off-diagonal inertia values.
2. Convert the URDF to USD format, ensuring that "Import Inertia Tensor" is checked.

 **Example URDF:**

```xml
<?xml version="1.0"?>
<robot name="test_robot">
  <link name="link1">
    <inertial>
      <mass value="1.0"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.1" ixy="0.1" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.2"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="1 1 1"/>
      </geometry>
    </visual>
  </link>
</robot>
```

**Expected Behavior:**
The intertia matrix in the URDF is

$$
I_2 = 
\begin{bmatrix}
0.1 & 0.1 & 0 \\
 0.1 & 0.1 & 0 \\
 0 & 0 & 0.2
\end{bmatrix}
$$

Which diagonalized becomes

$$ 
I_2 = R_Z(45\deg) \begin{bmatrix}
0.2 & 0 & 0 \\
 0 & 0 & 0 \\
 0 & 0 & 0.2
\end{bmatrix}
$$

The expected output would be then a rotation of 45° in the Z axis.

**Actual Behavior:**
The software diagonalizes the inertia matrix incorrectly but fails to compute the required rotation. Here is a screenshot of the imported robot.
![import_output](https://github.com/isaac-sim/urdf-importer-extension/assets/11806270/af91bc42-1c9e-4ff8-8168-914929b2190e)
 
It's clear that the rotation for the principal axis of rotation is zero degrees on all axes, which is wrong.

**Environment:**
- Ubuntu 20.04
- Isaac Sim 2023.1.1

**Conclusions**

As this may lead on very wrong behaviours in simulation, and if I didn't get anything wrong,  I think it is a critical issue.

Simone

**Comment by rgasoto** [comment]
Issue has been fixed for release 4.0
